### ISSUE TITLE
SocketError: Failed to open TCP connection to download.finance.yahoo.com:80

### ISSUE THREAD

**Issue by Victorcorcos** [timknight/stock_grabber#3]
# Steps to reproduce

1. Add `gem 'stock_grabber'` to Gemfile
2. `bundle install`
3. `rails c`
4. `stock = StockGrabber.new("GOOG")`

The result...

```rb
SocketError: Failed to open TCP connection to download.finance.yahoo.com:80 (getaddrinfo: nodename nor servname provided, or not known)
from /Users/victorcosta/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
Caused by SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/victorcosta/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
```

**Comment by timknight** [comment]
@Victorcorcos it seems the Yahoo API that this project uses has been defunct for 3.5 years. Since this project is largely unmaintained, knowing this I am know archiving the project as reference only.
